# Ativa a tela OLED
CONFIG_ZMK_DISPLAY=y

# Habilita o ZMK Studio (Mantendo a trava de segurança nativa)
CONFIG_ZMK_STUDIO=y

# Ativa os encoders rotativos
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
